### ISSUE TITLE
Documentation and Usage

### ISSUE THREAD

**Issue by RobertD502** [edc1591/python-iocare#1]
Just wondering if you happened to have written down any documentation regarding what variables need to be pre-filled prior to running & general use instructions?

**Comment by evandcoleman** [comment]
I'm still testing this with my air purifier and trying to work out some issues. It's high on my todo list to finish this up and write proper documentation, though!

**Comment by RobertD502** [comment]
I appreciate the quick response. Hopefully I can use it within Home Assistant to control/create sensors from select functions.

**Comment by evandcoleman** [comment]
That's the plan! I have a prototype HA component going already.
